### ISSUE TITLE
Lava energy generation chain

### ISSUE THREAD

**Issue by Frontrider** [CottonMC/Vivatech#17]
- [ ] Lava Generator 
- [ ] Lava Cooler

*By falseresync*
Lava Generator requires a block of lava to be placed on one side. Generator consumes it, gives energy and places cold lava on the other side. To start the cycle again it needs to have a new block of lava to be placed and the block of cold lava to be removed.
Lava Cooler requires a block of cold lava to be placed on one side. Machine consumes it, consumes coolant and throws a random amount of slug on the other side. To start the cycle again it needs to have a new block of cold lava to be placed.

**Comment by Frontrider** [comment]
I'd be curious what you have for solar. It has to require some sort of maintenance, or drawback outside "not working at night", or else you will have trouble with it. 
And it will also be uninteresting.

**Comment by TimGoll** [comment]
I like the maintenance aspect
maybe snow layers, wet patches and dust layers?

snow layers disable the panel completely
water patches reduce the efficiency, same thing with dust (which can be cleaned of with water)

but you have to think about glass blocks and other non-full blocks

**Comment by falseresync** [comment]
Yeah, I think I will do maintenance. Just count day rain-free ticks and cause breaks

**Comment by Frontrider** [comment]
It should be automatable, and detectable tough.
If you get it dirty, and the player have to wash it off with water, than there has to be a way to detect that it's happening. You could rely on observers to detect the time when you put down the dust, or detect the reduced energy input. A battery + a comparator could work well for that.

**Comment by TimGoll** [comment]
That's neat, or you flush it every night. You'd then need a light detector though

**Comment by Pannoniae** [comment]
Why is everyone obsessed with solar and lava? Seriously, these are the most boring energy sources you could ever find.

**Comment by Frontrider** [comment]
If he can make a solar that is not boring, than I call it a win.

Lava is only boring, if you can pump the nether with 2-3 blocks.

**Comment by TimGoll** [comment]
You could change the lavagenerator to a complex system. Like using lava to heat water, creating steam. using the steam to power a turbine, ... this could be interesing. additionally lava should generate some sort of waste you have to deal with

**Comment by Frontrider** [comment]
A waste that should also be a resource, or people will just void it.

**Comment by TimGoll** [comment]
fair point. Since lava is molten stone + ores one could use this to create ores and cobblestone

**Comment by Frontrider** [comment]
Would go for a special resource. The generator is not intended to be your quarry.

**Comment by falseresync** [comment]
I accept that idea. All of it (Lava -> Lava + Water + Waste)

**Comment by falseresync** [comment]
Simple solution to prevent lava gen being a quarry is to make the resource almost unique. Only two ways to get it - this and one more.

**Comment by TimGoll** [comment]
Additionally you could introduce a liquid "cooled" lava that has to be cooled further down to be used for a special resource.
"Cooled Lava" is the output of the geotermal generator. 

I you go the RedPower way of pipes you could say it is really viscous and needs a (electric) pump every x blocks. 

If you don't like that idea you could say that you need at least an electric pump at the exit of the geotermal generator so players can't skip the earlier generators to power up the geotermal generator

**Comment by falseresync** [comment]
Ofc

**Comment by LemmaEOF** [comment]
Lava power == free power due to the nether. I'm gonna shutter this to focus on other stuff.
