### ISSUE TITLE
Electric Furnace

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#2]
### Functions
- [x] Add a dummy machine (1a7d84b)
- [x] Make it hold smeltable items (not actual anymore, 415057b)
- [x] Make it hold energy (b140b57)
- [x] Make it smelt items and take energy (b140b57) (Broken e1bd520) (Fixed e1bd520)
### Interface
- [x] Add a dummy GUI (1a7d84b)
- [x] Add the burning indicator
- [x] Add energy bar
### Textures
- [x] Add block texture  (e1bd520)
- [x] Make it dynamic (415057b)

**Comment by Frontrider** [comment]
What "make it dynamic" means?

**Comment by falseresync** [comment]
Change texture depending on state, i.e. on and off textures
