### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TimGoll** [CottonMC/Vivatech#20]
So this is no bugreport but I want to suggest something.

A year ago I started creating a forge mod. My aim was to recreate the carpenters mod, but with a twist. I got carried away a bit and the result was an unfinished mod without carpenters blocks, but with water powered machines. In case you're interested, I'd like to merge them with your mod. 

Video: https://www.youtube.com/watch?v=Kng_nEyKI_c
Source: https://github.com/TimGoll/facading

My idea is to introduce a new layer of machines: water powered machines. They are used prior to coal powered machines, are slower and not that effective. Check out the video to see different machine types already implemented.

My ideas:
- a crusher that is soley powered by flowing water, but has only a chance of maybe 10 percent of ore doubling. But it allows for really early game alloying.
- an improved furnace, that runs on normal coal but allows for upgrades (more on that later)
- the machines can not be automated by using pipes, but a vanilla like automation should be possible. Maybe adding some blocks to your furnace under the water stream pulls items from the water inside the furnace
- a water powered press for gears and plates, that is slow and needs a template to press something
- maybe waterpowered generators, that are needed in order for the first coal generator to be crafted

The thing is, I could create my own mod, but I know that I would never finish it, because there are so many things that I want to do. And I like the concept of your mod. I'd be willing to implement said features by myself and open a PR for you to merge. But first I'd like to discuss this with you, if you're interested.

--
all videos:
1: https://www.youtube.com/watch?v=TeovwThqZrE
2: https://www.youtube.com/watch?v=pqzY-BkqKII
3: https://www.youtube.com/watch?v=ZJawohr3WMQ
4: https://www.youtube.com/watch?v=YOpT6GwQY00
5: https://www.youtube.com/watch?v=Kng_nEyKI_c

**Comment by falseresync** [comment]
Idea is good, but it poorly fits the mod. I think I would only introduce flowing water powered passive generators (Like Extra Utilities 2).

**Comment by TimGoll** [comment]
After thinking about this for a while, I might create my own mod based on this. Since it will use Cotton Resources, it will work together with your mod. 

Thanks anyway :)
