### ISSUE TITLE
Biofuel energy generation chain

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#24]
- [ ] Harvester
- [ ] Composter
- [ ] Fermenter
- [ ] Biofuel Generator

Harvester harvests the crops in the area to the front of it and consumes energy, hoes and fertilizer. It requires to be placed in front of the farmland blocks field with size from 1x1 to 9x9, supplied with sufficient amount of energy, hoes, seeds and fertilizer (optional for most crops).
Composter takes any kind of crop or food (each gives different amount of biomass) and produces biomass.
Fermenter takes biomass, water, sugar and energy and produces biofuel (liquid).
Biofuel Generator consumes biofuel and gives energy.

**Comment by LemmaEOF** [comment]
What increments should its range be in? 1x1, 3x3, 5x5, 7x7, 9x9? Also, should it only work with CropBlocks or also other plants as well?

Should the Composter work based on vanilla composter levels?

**Comment by falseresync** [comment]
1. No, any size should work, but if squares are easier to do, then ok
2. Eh, dunno 😃 The same as sizes, if it is easier to do, then do it
3. Composter has levels o_0

**Comment by LemmaEOF** [comment]
If it's just a max of 9x9 in an area in front of the harvester then that's easy. By "levels" I mean the float values that various blocks have been given that are a chance to fill the composter more. Maybe we can use those floats as percentages of a bucket of biomass?

**Comment by falseresync** [comment]
Neat idea 👍

**Comment by falkreon** [comment]
ha, it'd be cool if the harvester did a cone in front of it, but I don't think it'd be easy to explain to people who are used to square planters and harvesters.

**Comment by LemmaEOF** [comment]
I mean if we had a workspace visualization thing it wouldn't be too tough.

**Comment by falkreon** [comment]
Well if it winds up being circular planter and cone harvester, I have ideas for how to avoid spinning on non-work squares for both.

**Comment by falseresync** [comment]
What’s cone? Translator says it is the thing on the pine trees

**Comment by LemmaEOF** [comment]
![](https://res.cloudinary.com/dk-find-out/image/upload/q_80,w_960,f_auto/cone_x3fn44.jpg)

**Comment by falseresync** [comment]
Oh, that cone. I call it conus :D

Btw should be fine
