### ISSUE TITLE
Overheating mechanic

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#25]
It is simple: each machine overheats on its own rate. Once machine hit the overheat line it stops working until maintenance kit applied. Higher the tier of the machine and more upgrades are installed into it, faster it overheats. Static generators overheat at the fastest rate. To prevent overheating in machines you should stop a machine for a while or supply it with a liquid coolant. To prevent overheating in generators you could only supply them with coolant. Minimal tier machines and generators don’t overheat.

**Comment by LemmaEOF** [comment]
Hm, this might be an interesting idea for a maintenance mechanic. I'm not sure how *fun* it'd be, but we'll see.
