### ISSUE TITLE
Solar energy generation chain

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#26]
- [ ] Solar Boiler
- [ ] Steam Turbine

Solar Boiler takes water and during the day very slowly gives the steam. It breaks once in a while and remains so until the maintenance kit applied.
Steam Turbine takes steam and produces energy. It overheats tremendously.

**Comment by falkreon** [comment]
Any time someone says solar, I immediately go to this prior art -
https://vazkii.net/#blog/sins-of-a-solar-empire
https://www.youtube.com/watch?v=EitZRLt2G3w

Basically, solar power is extremely vulnerable to first-order optimization, which risks players starting at solar and then just never moving on from it to more complex or interesting mechanics.

**Comment by LemmaEOF** [comment]
I think we're gonna shutter this chain for now, we've got higher priorities and solar is *immensely* hard to do well.
