### ISSUE TITLE
Machines tiers

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#27]
Each machine should have 3 tiers: Minimal,
Normal and Advanced.
Minimal doesn’t overheat, has no upgrade slots, works slowly.
Normal slowly overheats, has 3 upgrade slots, works fast.
Advanced quickly overheats, has 5 upgrade slots, works very fast.

**Comment by snakefangox** [comment]
I'm going to be taking a shot at this one.

**Comment by Frontrider** [comment]
I'd recommend storing the tier in the blockstate, as I assume that you're going to use it to render it as well anyways.

**Comment by falseresync** [comment]
No, do separate blocks with the same BlockEntity. That would fit vanilla a lot more

**Comment by LemmaEOF** [comment]
yeah, with the Flattening, there's not really any need for keeping it on the state anymore, especially with the new method for registering block entities that takes a list of blocks

**Comment by Frontrider** [comment]
You know what. It does sound better that way, especially if you want to extend the system.

**Comment by Pannoniae** [comment]
If advanced overheats, why would anyone use it instead of 3 minimal machines?

**Comment by falseresync** [comment]
Recipes. Also, much faster and more upgrades slots available

**Comment by Frontrider** [comment]
You meant to automate the cooling. In which case you don't care.

Same as not caring about the power requirements of late game machines.

**Comment by falseresync** [comment]
Yeah, @Frontrider is right. It will definitely be automatable
