### ISSUE TITLE
Copy Cotton’s recipe code

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#30]
Cotton is going to get rid of cotton.datapack.recipe pkg so the code from here needs to be moved to Vivatech

**Comment by Juuxel** [comment]
CottonMC/cotton#29 can be moved as well.

**Comment by LemmaEOF** [comment]
Specifically, we're moving the crushing recipe out, because crushers are way too abstract for that.

**Comment by falseresync** [comment]
Yeah

**Comment by LemmaEOF** [comment]
Absorbed!
