### ISSUE TITLE
crash on load (1.14.2 fabric build 2)

### ISSUE THREAD

**Issue by SDUBZ** [CottonMC/Vivatech#33]
**Describe the bug**
Crash on load with  vivatech-1.0.0-alpha.6+1.14.2 and cotton-0.7.4+1.14.2-SNAPSHOT

**To Reproduce**
1. Go to load with mentioned mods and dependencies 
2. wait for it to crash due to recipe bugged out

**Expected behavior** *Optional*

**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - vivatech-1.0.0-alpha.6+1.14.2
 - cotton-0.7.4+1.14.2-SNAPSHOT
 -cotton-energy-1.3.2+1.14.2-SNAPSHOT
 - fabric-api-0.3.0+build.183
 - Minecraft 1.14.2

crash report:
[crash-2019-06-12_13.50.54-client.txt](https://github.com/CottonMC/Vivatech/files/3279585/crash-2019-06-12_13.50.54-client.txt)

**Additional context** *Optional*

**Comment by Juuxel** [comment]
Should be fixed in 3487fc23.

**Comment by SDUBZ** [comment]
any estimate on release just curious

**Comment by falseresync** [comment]
Use older Cotton right now. Alpha 7 is coming in a few days, estimate stable release date is September.
