### ISSUE TITLE
Energy Conduits don't transfer energy

### ISSUE THREAD

**Issue by MarioAndWeegee3** [CottonMC/Vivatech#42]

**Comment by falseresync** [comment]
May you provide more information? We know about the bug, but doesn’t know when exactly it happens

**Comment by MarioAndWeegee3** [comment]
I have these mods:

- cotton 1.7.4
- fabric api 0.3.0 185
- vivatech 1.0.0 alpha 8

![2019-06-20_08 16 40](https://user-images.githubusercontent.com/35458805/59848813-15830000-9334-11e9-992d-fea77b356af8.png)

**Comment by falseresync** [comment]
Does energy transfer from gen to machine without a conduit? 

Does energy transfer when the machines are on other coordinates and face other direction (NWSE)?

**Comment by MarioAndWeegee3** [comment]
Energy does transfer without a conduit

I wasn't able to get the conduits to transfer at other coordinates/directions

**Comment by falseresync** [comment]
Thank you for your collaboration. The issue is being fixed right now

**Comment by falseresync** [comment]
Should be fixed in Vivatech 1.0.0 Alpha 10
