### ISSUE TITLE
Cobalt

### ISSUE THREAD

**Issue by edeetee** [CottonMC/Vivatech#45]
No documentation on how to find Coabalt. Could you add something to the wiki pls?

**Comment by falseresync** [comment]
That’s from Cotton Resources. It might be disabled in its config. Try to tinker it, if you still can’t find it neither in overworld nor in nether, then reopen the issue

**Comment by edeetee** [comment]
Is there a way to edit the config without rebuilding the mod? Can't find anything in the documentation about an easy way to do it.
Or if I want to use this in survival should I just wait for an update?

**Comment by falseresync** [comment]
Did you try to find cobalt ore in other dimensions?

Do you have other ores like copper from Cotton Resources?

Did you try to edit Cotton and Cotton Resources configs in .minecraft/config?

**Comment by edeetee** [comment]
Okay I found the config, thanks :)
I'm new and didn't know there was a config directory. Somehow I made my mod without figuring that out haha.
I have the other ores from cotton. They aren't being used for anything.
Now if there was only a way to regenerate the world I started ;(

**Comment by falseresync** [comment]
Yeah, that thing about world sucks. Try it again now, better in creative to spend less time, if you still have the issue let me know here

**Comment by falseresync** [comment]
P.S. you may use /fill ... replace ... to remove stone from chunks
P.P.S. More on MC Wiki
