### ISSUE TITLE
Pollution

### ISSUE THREAD

**Issue by falseresync** [CottonMC/Vivatech#46]
You know what it is

**Comment by falkreon** [comment]
We've built a powergen event into cotton-energy, which we may or may not have to tool up, but over on the UM side we're going to fire it to indicate consumption of fossil fuels. FYI.

**Comment by falseresync** [comment]
I may use it. I would also like to have power consumption callback

**Comment by falkreon** [comment]
Power consumption almost never triggers any kind of greenhouse gas emission. It'd probably be better to have an environmental damage event, with a map of types (heat, airborne-particulate-matter, greenhouse-gas, ionizing-radiation, groundwater-pollution, chaos-magic, unbound-arcana) with some guidelines to quantify them. Then machines and devices can give a much more nuanced description of the kinds of external impact they have when they operate.

**Comment by falseresync** [comment]
I dunno if I want to load the game that hard, I am afraid all of those calculations on each chunk to produce pollution effects would be tremendous performance loss

**Comment by Frontrider** [comment]
You only need a system like that if you have multiple mods doing similar things.

**Comment by falseresync** [comment]
?

**Comment by Frontrider** [comment]
That is for falk's concept.

**Comment by falseresync** [comment]
Ah

**Comment by falkreon** [comment]
Well that depends. Throwing an event for each of these things would be quick work. Calculating one versus seven pollution types for diffusion from one chunk to one other chunk would be roughly the same work. Calculating diffusion across a plane, in general, is a tough game, even with one "generic pollution" type. That's where you get into the O(m*n) complexity.

So if you're considering modeling pollution diffusion at all:
* Focus diffusion activity around player locations. If this creates hard walls of pollution-against-no-pollution where players never go, who cares?
* One pollution type versus seven will probably not make any difference
* Don't calc the entire world's diffusion inside of a single world tick. It would be a disaster. I see people struggle with this a lot for large explosions, too. Run a worker, splitting up the diffusion task into chunk-sized pieces and calculating a hard-capped number of chunks per server tick.
* Consider larger diffusion "chunks" than standard world chunks. Regions are a little mean, but they sure would reduce the search space, and force people to make hard sacrifices if they bail on a polluted area.

Consider non-cellular approaches. An alternative model might be circular pollution zones. If a polluter is within the circle, drag the circle center towards the additional polluter and dump the pollution into the existing circle. If two circles touch, slowly drag them towards each other. If their centers manage to come within X meters of each other, merge them into a zone with the sum of their pollution. This will center pollution clouds properly over factories and can slowly spread out even through unloaded chunks, all in more or less O(1) time. The tradeoff is that lookup from a blockpos to relevant pollution zones might be an O(n) lookup. This could be solved with a quadtree but probably isn't *worth* a quadtree unless you get to hundreds of zones.

**Comment by falseresync** [comment]
Wow, that’s a huge of a concept, thank you very much!
