### ISSUE TITLE
No Cobalt Nugget Recipe

### ISSUE THREAD

**Issue by JustJinxed** [CottonMC/Vivatech#48]
Placing a Cobalt Ingot alone in craft area doesn't produce a nugget. So neither cotton resources or Vivatech is handling it? 

Vivatech: vivatech-1.0.0-alpha.9+1.14.2
Cotton Resources: cotton-resources-1.2.2+1.14.2
Cotton: cotton-0.8.3-pre+1.14.3

**Comment by falseresync** [comment]
Should be fixed in Cotton Resources 1.3.3
