### ISSUE TITLE
Energy Banks have infinite energy when given power through a conduit

### ISSUE THREAD

**Issue by Super-Shadow** [CottonMC/Vivatech#52]
When using an energy conduit to link an energy bank and a coal generator together, the energy bank appears to have 1J stored, but it never depletes. Not only that, but the coal generator keeps getting depleted of energy, though the Energy Bank's joules never increase. This allows for infinite energy and is overpowered. This 1J can be taken out of the Energy Bank by using a Battery. Placing the Battery back into the Energy Bank will give it infinite energy again. This only happens when using a conduit to connect them together as placing them side by side works normally.

Steps to reproduce the behaviour:
1. Place a Coal Generator down and connect it to an Energy Bank via an Energy Conduit
![image](https://user-images.githubusercontent.com/9903072/61870165-58a53580-aed5-11e9-9197-eb8ed6e1f606.png)
2. Place coal in the Coal generator
![image](https://user-images.githubusercontent.com/9903072/61870185-6955ab80-aed5-11e9-8ba2-6a59ded4aa8a.png)
![image](https://user-images.githubusercontent.com/9903072/61870196-72df1380-aed5-11e9-94a3-c1691d890ebc.png)
3. Destroy the Coal Generator and replace it with a machine
![image](https://user-images.githubusercontent.com/9903072/61870219-7e323f00-aed5-11e9-8a9f-037250919eee.png)
4. Observe the machine be fully powered while the Energy Bank stays at 1J
![image](https://user-images.githubusercontent.com/9903072/61870244-85f1e380-aed5-11e9-9d96-12e9e494ba1b.png)
![image](https://user-images.githubusercontent.com/9903072/61870256-8be7c480-aed5-11e9-8041-48fb4b4a3b0b.png)

 - vivatech-1.0.0-alpha.10+1.14.4
 - cotton-1.0.0-rc.2
 - cotton-resources-1.3.3+1.14.3
 - cotton-energy-1.5.0+1.14.3-SNAPSHOT
 - fabric-api-0.3.0+build.200
 - libblockattributes-all-0.4.9
 - LibGui-1.1.0
 - Jankson-1.0.0+j1.1.2
 - Minecraft - fabric-installer-0.5.0.33

**Comment by Super-Shadow** [comment]
Upon further testing, it seems like the energy bank's stored energy does not decrease when energy is being transferred via a conduit.

**Comment by falseresync** [comment]
Hi! Thank you for submitting an issue. I am aware of Conduits stupidity; I am working on a full revamp right now.

P.S. You only need Fabric API and Cotton, else is included :)

**Comment by Super-Shadow** [comment]
Ahh right thank you for the advice!

**Comment by falseresync** [comment]
Thank you for your contribution! It is really important for me to get constructive feedback. Feel free to reopen it if you encounter the issue again
