### ISSUE TITLE
Game Crash / Crash on Savegame Load

### ISSUE THREAD

**Issue by ExoFrece** [CottonMC/Vivatech#54]
I Place Vivatech Machine and the Game Crash
after that I can not access the world anymore

Minecraft 1.14.4

Mods:
cotton-1.0.0-rc.2
cotton-resources-1.4.0+1.14.4
fabric-api-0.3.0+build.200
modmenu-1.6.3+build.101
RoughlyEnoughItems-2.9.7+build.143
vivatech-1.0.0-alpha.13+1.14.4

[latest.log](https://github.com/CottonMC/Vivatech/files/3438348/latest.log)

**Comment by falseresync** [comment]
Is it a new world or an existing one? 
You don't need to manually install Cotton and Cotton Resources anymore

**Comment by ExoFrece** [comment]
its a new world 
I always test with newly generated worlds

**Comment by falseresync** [comment]
Thank you, I've recognized an issue and working on a fix right now! Expect mod update in roughly an hour or two

**Comment by ExoFrece** [comment]
must i open a new issue for another bug?
I do not know if it's a bug from viva or RoughlyEnoughItems or maybe even CR?
The steel recipe don't show

**Comment by falseresync** [comment]
That is mine bug too :wink: Fixing

**Comment by ValerieTheBun** [comment]
Had the same issue, repeatedly reproduced. Here's the log from trying to place the crusher the first time. Hopefully it helps.

[mc_ctd_crashlog.txt](https://github.com/CottonMC/Vivatech/files/3438379/mc_ctd_crashlog.txt)

Mods:
Fabric API 0.3.0+build.206
Roughly Enough Items 2.9.7+build.143
Vivatech 1.0.0-alpha.13+1.14.4
The One Probe 1.4.29.beta

**Comment by falseresync** [comment]
Thank you! I am publishing a fix right now

**Comment by falseresync** [comment]
Fixed in Alpha 14
