### ISSUE TITLE
Crusher doubling not consistent

### ISSUE THREAD

**Issue by ValerieTheBun** [CottonMC/Vivatech#55]
Sorry, I know you literally just pushed this release.

**Describe the bug**
When processing ores in the crusher, ores only produce 2 of the respective dust if there is nothing in the output slot, otherwise, each ore only produces 1 dust when something is present in the output slot.

**To Reproduce**
1. Put an ore into the Crusher's input slot
2. Get two ore dust
3. Put another ore in without removing the two dust from before.
4. Only get a third dust

**Expected Behaviour**
I would assume that the idea is to double every ore, not just the first one.

**Screenshots**
![2019-07-27_13 36 56](https://user-images.githubusercontent.com/1123045/61997710-de5ee780-b073-11e9-977a-9d6aa3878ff3.png)
![2019-07-27_13 37 07](https://user-images.githubusercontent.com/1123045/61997711-de5ee780-b073-11e9-9e1e-a565fec4de37.png)
![2019-07-27_13 37 14](https://user-images.githubusercontent.com/1123045/61997712-de5ee780-b073-11e9-9073-c2a8818f838f.png)

No crash related, and nothing showed about this in the logs.

Minecraft Version 1.14.4
Mods:
Fabric API 0.3.0
Roughly Enough Items 2.9.7+build.143
The One Probe 1.4.29.beta
Vivatech 1.0.0-alpha.14+1.14.4

**Comment by ValerieTheBun** [comment]
Forgot to note in the main post that it will continue to only make one dust per ore past this point if the output slot isn't cleared, and that the 1:1 output isn't limited to just the second ore processed.

**Comment by Juuxel** [comment]
At a glance, this line looks like the cause:
https://github.com/CottonMC/Vivatech/blob/21a6877017dd6c860d2f3acb91ba0363d3aaf260/src/main/java/vivatech/common/block/entity/CrusherBlockEntity.java#L137

**Comment by falseresync** [comment]
Thank you for submitting the issue and helping me find out the cause! This is a typical copy-paste error I should be embarrassed of. Expect fix 28 Jul, London time
